comprodls-data/test-performance

- Get_global_entitlements_of_a_user.jmx
Get Global Entitlements API Fragment - Updated and Cleaned
> Get Global Entitlements API Fragment - Updated and Cleaned

- Get_classes_of_an_user.jmx
updated Get_classes_of_an_user.jmx
> Get_classes_of_an_user.jmx

- Get_an_access_token_for_an_external_user.jmx
- Get_an_access_token_for_an_external_user_institution.jmx
updated Get_an_access_token_for_an_external_user_institution.jmx
> updated Get_an_access_token_for_an_external_user_institution.jmx

- Join_Spaces_with_product_code_and_class_code.jmx
> Payload Schema updated and disabled component removed

- Join_Spaces_with_product_code_and_class_code_private.jmx
> Payload Schema updated

- Get_product_by_product_code.jmx
updated extractors and assertion
> Get Product by Product Code

- Get_details_for_a_specific_class.jmx
updated assertion  and extractors and removed one extraactor
> updated assertion and extractors

- create_new_instructor_led_class.jmx
1. Parameter name updated
2. Assertion added
> Parameter name updated and assertion added

- Get_enrollments_of_users_in_class.jmx
> Update parameter name

- Get_user_application_state_for_a_product_or_class_product_.jmx
- Get_user_application_state_for_a_product_or_class_product_private.jmx
- Get_user_application_state_for_a_product_or_class_product_student.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code_evaluated.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code_private.jmx
updated extractors and assertions
> updated extractors and assertions

- associate_a_product_with_class.jmx
- associate_a_product_with_class2.jmx
1. Added If condition for single or multi product
> Associate product with class

- Entitle_User_With_Product_Code.jmx
- c1_perf_test_all_scenario.jmx
1. product_code is updated to productcode 
2. start and end date also updated
3. Ref ID value updated to ext_user_id
> API Updated

- Get_a_Particular_Bundle.jmx
- c1_perf_test_all_scenario.jmx
committing new api get a particular bundle
> Get a Particular Bundle

- update_user_information.jmx
1. Payload updated... Removed ext role
> Update user info

- class_pending_submissions.jmx
- class_pending_submissions_1027.jmx
- class_pending_submissions_NEW_product.jmx
> added assertion in all the three files

- Group_Pending_Submissions_of_a_Class.jmx
> added new file for group pending submissions of a class

- Get_multiple_invitations_by_context_id.jmx
New Script  - Get multiple invitations by context
> New Script  - Get multiple invitations by context

- Update_user_application_state_for_a_product_or_class_product_evaluated.jmx
- Update_user_application_state_for_a_product_or_class_product_private.jmx
- Update_user_application_state_for_a_product_or_class_product_with_item_code.jmx
updated test fragment name and variable name
> Update user's app state of a product or class product

- 1003-Student_logs_in_and_accesses_the_dashboard.jmx
- 1003-Student_logs_in_and_accesses_the_dashboard_Private.jmx
1. added controllers 
2. Replaced controllers not being used now
> Scenario 1003 - Institutional and Private

- Product_items_and_their_progress_analytic_default.jmx
- Product_items_and_their_progress_analytic_default_Group_True.jmx
- Product_items_and_their_progress_analytic_default_History_True.jmx
- Product_items_and_their_progress_analytic_default_With_ItemCode.jmx
- Product_items_and_their_progress_analytic_default_evaluated.jmx
1. Added If condition for single or multi type product
2. Added 2 New specific fragments for group=true and history=true
> Added classProductType If condition And New Fragments

- Get_all_bundles.jmx
1. Request Path Updated
2. assertion Updated
> Updated Path and Assertion

- 1014-Teacher_logs_in_and_accesses_the_dashboard.jmx
> Scenario 1014

- Unassociate_a_product_from_a_class.jmx
1. Added If Condition for single or multi product
2. Added assertion
> Added If condition and Assertion

- Get_information_for_a_specific_user.jmx
> Added New API

- c1_perf_test_all_scenario.jmx
1. Updated beanshell script
2. Added "Get Assigned paths of a user" and disabled it.
3. Added "get classes of a user" and disabled it.
4. Added call for "API to grant auth key"
5. Added call for "Product Items and their Progress Analytics".
6. Added call for "Get Global Entitlements of user".
7. Enabled call for "Get All user user spaces".
> Scenario 1001

- Get_all_users_in_org.jmx
> Added Assertion

- Join_Spaces_with_product_code_and_class_code.jmx
- Product_items_and_their_progress_analytic_default.jmx
- c1_perf_test_all_scenario.jmx
- validate_classcode.jmx
1002: Student registers using a class key & access code  (and access default or first time dashboard) - New Users
1. Updated beanshell script
2. Enabled "Get All user user spaces".
3. Added changes done in 1001
4. Added "Validate Class code".
5. Added "Get enrolments of users in a class".
6. Added "Get_details_for_a_specific_class".
7. Removed "Get list of all products for a user".
8. Changed name of "Get_list_of_assignments_assigned_to_a_learner_in_class" to "Get assigned paths of a user in a class"
9. "bzm - Random CSV Data Set Config"
- Changed classcodeinst to "classcode".
10. Added udv for "productType"
File "Validate_classcode. jmx"
1. Changed "class_code" to classcode
2. Changed assertion to exists
3. Extracted classid
"Join Spaces with product_code and class_code"
1. Changed …
> updated scenario 1002 and related fragments

- update_details_of_class.jmx
1. Payload Updated
2. Assertion Updated
> Payload and Assertion Updated

- Get_class_level_aggregations_for_all_items_in_a_assigned_path.jmx
> Get class level aggregation for all items

- Get_all_assigned_paths_of_a_class.jmx
1. Enabled Fragment
2. Enabled Assertion
> Enabled Fragment and Assertion

- c1_perf_test_all_scenario.jmx
1. Added "Get Global Entitlements of a user".
2. Added "API to grant authkey on refid".
3. Added "Product items and their progress analytic (default)" in place of "Get list of all products for a user" and enabled it.
> updated c1_perf_test_all_scenario.jmx

- unenroll_multiple_users_into_class.jmx
> Assertion added

- Join_Spaces_with_class_code.jmx
- Product_items_and_their_progress_analytic_default_product2.jmx
- c1_perf_test_all_scenario.jmx
1. Added "Get Global Entitlements of a user", "Get an access token for an external user"
2. Added "Product items and their progress analytic (default)" in place of "Get list of all products for a user" and enabled it.
3. Changed value for external product id in User defined variables.
4. Added file "Product_items_and_their_progress_analytic_default_product2.jmx" for product2
5. Used reference for "Get All Assigned Paths of a learner in a class_noassignedPaths".
> updations for scenario 1005

- 1014-Teacher_logs_in_and_accesses_the_dashboard.jmx
- c1_perf_test_all_scenario.jmx
- class_pending_submissions.jmx
- class_pending_submissions_1027.jmx
Scenario 1017: Teacher can review / open learning path of products available in that institution
1.  c1_perf_test_all_scenario.jmx
- Removed fragment "Get_product_by_product_id.jmx" and Added "Get_product_by_product_code.jmx"
2. 1014-Teacher_logs_in_and_accesses_the_dashboard.jmx
- Comment updated
3. class_pending_submissions.jmx
- Removed variable "flag" and added hard coded value as "false"
4. class_pending_submissions_1027.jmx
- Removed variable "flag" and added hard coded value as "true"
> Scenario 1017 updated

- c1_perf_test_all_scenario.jmx
Scenario 1018: Teacher creates a new class in a particular institution
- Removed UDV as start Date and End Date are already defined in Global UDV
- Updated Beanshell Preprocessor - Classname is now as per finalized format
- Added Fragment "API_to_grant_authkey_on_refid.jmx"
- Removed Fragment "Get_details_for_a_specific_class.jmx"
- Removed Fragment "Get_all_the_User_Spaces.jmx"
- Removed Fragment "Get_classes_of_an_user.jmx"
- Removed Fragment "Get_all_bundles.jmx"
- Removed Fragment "Get_global_entitlements_of_a_user.jmx"
> Scenario 1018 fixed

- c1_perf_test_all_scenario.jmx
Scenario 1025: Teacher can review class progress - for all student in that class
- Removed UDV as flag is not required (already defined in class_pending_submission)
- Added fragment "API_to_grant_authkey_on_refid.jmx"
- Added fragment "API_to_grant_authkey_orgid.jmx"
- Added fragment "Get_all_the_User_Spaces.jmx"
- Disabled fragment "Get_global_entitlements_of_a_user.jmx" (Not valid for this scenario)
- Added fragment "Get_classes_of_an_user.jmx"
- Removed fragment "Analytics_for_items_product_in_a_class_aggregrated_over_all_students_in_that_class.jmx"
- Added dummy fragment "Class Group Recent Pending Submission"
- Added fragment "Get_multiple_invitations_by_context_id.jmx"
- Added dummy fragment "Get all groups by path"
- Added dummy fragment "Get all …
> Scenario 1025 updated

- Get_user_application_state_for_a_product_or_class_product_.jmx
- Get_user_application_state_for_a_product_or_class_product_private.jmx
- Get_user_application_state_for_a_product_or_class_product_student.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code_evaluated.jmx
- Get_user_application_state_for_a_product_or_class_product_with_item_code_private.jmx
- c1_perf_test_all_scenario.jmx
1. Changed "Get product by product id" to "Get product by product code".
2. Changed assertion to inverse assertion ($.dbErrorBody) in files "Get_user_application_state_for_a_product_or_class_product_private.jmx" and "Get_user_application_state_for_a_product_or_class_product_with_item_code_private.jmx".
> updates for scenario 1008 and related fragments

- Get_global_entitlements_of_a_user_by_teacher.jmx
- c1_perf_test_all_scenario.jmx
Scenario 1026: Teacher can review class progress - one students in that class
- Removed fragment "Analytics_for_users_in_a_class_aggregrated_over_all_the_items_materials_product_in_that_class.jmx"
- Removed fragment "Get_information_of_a_product_for_a_user_teacher.jmx"
- Added fragment "Get_information_for_a_specific_user.jmx"
- Added fragment "Get_global_entitlements_of_a_user_by_teacher.jmx"
2. Get_global_entitlements_of_a_user_by_teacher.jmx
- Added new file to support Get Global entitlment call for learners from teacher view
3. Get_information_for_a_specific_user.jmx
- Parameters name updated
> Scenario 1026 updated

- 1008-Student_accesses_the_learning_path_of_a_product_self-paced_.jmx
- c1_perf_test_all_scenario.jmx
1. Updated file 1008-Student_accesses_the_learning_path_of_a_product_self-paced_.jmx.
2. Removed extra call for "Update_user_application_state_for_a_product_or_class_product_private.jmx"
> updates for scenario 1010

- Entitle_User_With_Product_Code2.jmx
- c1_perf_test_all_scenario.jmx
Updates:
1. Entitle-user-with-product2: updated parameter name from 'classproductype' to 'producttype'
2. Included
-  'Get a particular **Bundle' 
-  'Get Global Entitlements of a user'
- 'Get an access token for an external user'
- 'Product_items_and_their_progress_analytic_default_private' 
3. Removed 
- 'Get list of all products for a user'
-  Disabled listener from scenario 1006
> updated scenario 1006

- 1009-Student_accesses_the_learning_path_of_a_product_as_part_of_a_teacher-led_class.jmx
- Product_items_and_their_progress_analytic_default_Group_True.jmx
- c1_perf_test_all_scenario.jmx
1011:
1. "1009-Pre" - Changed "Get product by product id" to "Get Product by product code".
2. "1009-pre" - Re-ordered "Get product by product code" and "Product items and their progress analytic (default)".
3. Changed reference file to "Product_items_and_their_progress_analytic_default_Group_True.jmx".
4. Added call for "Delete users application state for a product or class(product)".
5. Removed extra call for "Update user's application state for a product or class (product)".
6. Changed value for "productGroups" to "true" in master udv.
7. "Product_items_and_their_progress_analytic_default_Group_True" - Added if controllers for "productGroups" to be "true" and "false"
> Scenario 1011

- c1_perf_test_all_scenario.jmx
1. Removed extra call for "Update user's application state for a product or class (product)".
2. Re-ordered "Update user's application state for a product or class (product)".
3. Re-ordered "Product-pskill-item-progress-analytic".
> updates for scenario 1012

- associate_a_product_with_class2.jmx
- c1_perf_test_all_scenario.jmx
1. Removed extra request - Get product by productcode
2. associate product with class2 updated for parameter name 'classProdutType' to 'productType'
3. Added API grant auth key
> Updated scenario 1019

- c1_perf_test_all_scenario.jmx
- update_details_of_class.jmx
1. Added 'API to grant authkey'
2. Added 'Get multiple invitations by contextid'
3. Added dummy 'Get all groups by group path'
4. Added 'Get details for a specific class'
5. Added dummy 'Get all the members of the group, along with its child groups and their memberships.'
6. Updated fragment 'update details of class' for new class name. Added extuserid in new class name
> Updates for scenario 1020

- 1014-Teacher_logs_in_and_accesses_the_dashboard.jmx
- c1_perf_test_all_scenario.jmx
Updates:
1. Disabled 'Class pending submissions' in pre1014
2. Other minor updates
> Updated scenario 1021

- c1_perf_test_all_scenario.jmx
1. Added call for "Get details for a specific class.".
> update for scenario 1037

- c1_perf_test_all_scenario.jmx
1. Chnaged "Get product by product id" to "Get product by product code".
2. Added call for "Get groups for the learner in a class in case of groups enabled product" and disabled it.
3. Removed an extra call for "Student views his all Assignments Aggregations".
4. Changed reference file to "Product_items_and_their_progress_analytic_default_Group_True.jmx".
> changes for 1038_npskill

- c1_perf_test_all_scenario.jmx
1. Chnaged "Get product by product id" to "Get product by product code".
2. Added call for "Get groups for the learner in a class in case of groups enabled product" and disabled it.
3. Removed an extra call for "Student views his all Assignments Aggregations".
> updates for scenario 1038 pskill

- Create_an_assigned_path_in_a_class.jmx
- c1_perf_test_all_scenario.jmx
1039: Teacher creates an assignment
- Updated global UDV for Item Code 2 and Item Code 3 value (Product: evpel1)
- Updated Beanshell Preprocessor to update assignment title
- Updated Fragment from "Get_product_by_product_id.jmx" to "Get_product_by_product_code.jmx"
- Added dummy disabled If controller and fragment for Group Products
2. Create_an_assigned_path_in_a_class
- Updated Assignment Start and End Date variable values
> Scenario 1039 updated

- c1_perf_test_all_scenario.jmx
1024: Teacher enrolls and removes other teachers from the class
- Removed UDV as flag variable is not required
- Added fragment "API_to_grant_authkey_on_refid.jmx"
- Added fragment "API_to_grant_authkey_orgid.jmx"
- Added fragment "Get_multiple_invitations_by_context_id.jmx"
- Added fragment "Get_details_for_a_specific_class.jmx"
- Removed fragment "Analytics_for_items_product_in_a_class_aggregrated_over_all_students_in_that_class.jmx"
- Removed fragment "Get_all_users_in_org.jmx"
- Removed fragment "Get_global_entitlements_of_a_user.jmx"
> Scenario 1024 updated

- Group_Pending_Submissions_of_a_Class.jmx
- c1_perf_test_all_scenario.jmx
1. Used "Get_Alluser_spaces_nospaces" instead of "Get_All_user_spaces"
2. Added call for "Join Spaces with Space Code".
3. Added call for "API to grant authkey on refid" and "api to grant authkey(orgid)"
4. Added call for "Join Spaces with space_code", "Get access token of new student".
5. Not added calls in row no 13 and 14.
6. Added call for "Get_all_the_User_Spaces.jmx", "Get Global Entitlements of a user"(disabled), "Get_classes_of_an_user", "Get all the workflow requests, made by a particular user" and "Get All bundles" , "Class Pending submissions" , "Class group recent pending submission".
7. File "Group Pending submission of a class", added if controller for "ProductGroup" (for dev notes present for the call - "Called only in case of collaborate product( which has groups.enabled …
> updates for scenario 1045

- c1_perf_test_all_scenario.jmx
1. Added call for "API to grant authkey on refid" and "api to grant auth key(orgid)"
2. Added call for "Join Spaces with space_code", "Get access token of new student".
3. Not added calls in row no 13 and 14.
4. Not Added call for "Join Spaces with Space Code".
5. Disabled call for "validate class code"
6. Added call for "Get_all_the_User_Spaces.jmx", "Get Global Entitlements of a user"(disbaled), "Get_classes_of_an_user", "Get all the workflow requests, made by a particular user" and "Get All bundles" , "Class Pending submissions" , "Class group recent pending submission".
> updates for scenario 1044

- 10461.csv
- c1_perf_test_all_scenario.jmx
1046: Teacher can review class progress - for all student in an expired class - New Scenario Added
Key Points:
1. Similar to Scenario 1025 but only called for expired class
2. Throughput is currently set to 1.0
3. Dummy CSV Data file also committed 
4. "Get_all_the_User_Spaces.jmx" And "Get_classes_of_an_user.jmx" is called as a part of fragment 1014 as well as in the Scenario. Please review
> New Scenario 1046 added

- c1_perf_test_all_scenario.jmx
1040: Teacher views Class Assignments Aggregations
- Removed UDV as flag variable is not required
- Removed fragment "Analytics_for_users_in_a_class_aggregrated_over_all_the_items_materials_product_in_that_class.jmx"
- Removed fragment "Get_members_of_a_class.jmx"
- Added fragment "Get_product_by_product_code.jmx"
- Added fragment "Get_details_for_a_specific_class.jmx"
- Added fragment "Deletes_user_application_state_for_a_product_or_class_product_1027.jmx"
> Scenario 1040 updated

- c1_perf_test_all_scenario.jmx
- class_pending_submissions.jmx
- class_pending_submissions_1027.jmx
Updated Assertion and Added If condition in c1 file
> Added conditions

- Create_a_new_group.jmx
- Get_all_members_of_the_group.jmx
- c1_perf_test_all_scenario.jmx
- class_group_pending_submissions.jmx
1. New Scenario Added
2. Currently it is disabled
3. Assertion might need an update once this will be functional
> Scenario 1051 added

- Get_all_the_groups_by_path_1054.jmx
- c1_perf_test_all_scenario.jmx
- class_group_pending_submissions_details_true_1054.jmx
- class_pending_submissions_group_details_true.jmx
Two fragments specific to 1054
Disabled extraction of student userid
> committing the changes for 1054..two new fragments

- Get_all_my_memberships_by_path.jmx
- c1_perf_test_all_scenario.jmx
Changes in c1 file for 1009_grp scenario
> scenario 1009 for grp

- Get_members_of_a_class_group_1052.jmx
- c1_perf_test_all_scenario.jmx
> Scenario 1052

- Get_metadata_of_the_specific_group.jmx
- add_items_to_showcase.jmx
- c1_perf_test_all_scenario.jmx
- get_showcase_of_a_class.jmx
> Added fragment and apis for Showcase scenario
